function buildExplainPrompt({
  systemPrompt,
  commandGuidance,
  safetyRequirements,
  detailTemplate,
  commandRules,
  userInput
}) {
  return [
    systemPrompt,
    '',
    'Output format requirements (strict):',
    '- Return exactly 5 H2 sections using these headings in this order:',
    '  1) ## Chunk 1/5: Concept Summary',
    '  2) ## Chunk 2/5: Foundational Basics',
    '  3) ## Chunk 3/5: Core Technical Breakdown',
    '  4) ## Chunk 4/5: Defensive Use Cases',
    '  5) ## Chunk 5/5: Safe Basic Commands (Authorized Lab Environments Only)',
    '- Keep each chunk concise and actionable (target ~60-120 words per chunk).',
    '- Keep every chunk directly tied to the user request. Do not switch to a different topic.',
    '- Include at least 2 fenced code blocks when commands/snippets are relevant to the concept.',
    '- If the concept is not command-heavy, use checklists and concrete steps instead of forcing shell commands.',
    '- Chunk 3 and Chunk 4 must contain practical technical and defensive analysis tied to the requested concept.',
    '- Start directly with "## Chunk 1/5: Concept Summary".',
    '',
    'Teaching style requirements:',
    '- Assume the learner is beginner unless they ask for advanced only.',
    '- Explain jargon before using it in depth.',
    '- Use markdown headings and bullet points.',
    '- Do not use markdown tables; prefer headings and "-" bullets for Discord readability.',
    '- Put any query/payload/command snippet in fenced code blocks for easy copy in Discord.',
    '- Use one list style at a time: either numbered list or "-" bullets, never mixed on the same item.',
    '- Never output list markers like "- 1." or "• 1."; use clean "1." numbering when steps are sequential.',
    '- Keep step labels concise (for example: "1. **Validate Input:** ...").',
    '- Do not add chatty intro lines or extra sections outside the 5 required chunks.',
    '- Keep sections practical, specific, and easy to follow.',
    '- Include actionable safe examples where relevant.',
    '- Keep output detailed and topic-focused. Remove generic filler and off-topic content.',
    '',
    'Safety requirements:',
    ...safetyRequirements,
    '',
    'Depth requirements:',
    '- Provide practical depth with enough detail for safe hands-on learning.',
    '- Prefer concrete, concept-specific guidance over generic theory.',
    '- If commands are included, keep them authorized-lab safe and directly relevant to the concept.',
    '- Use concise paragraphs and bullet lists for readability.',
    '',
    detailTemplate,
    commandRules ? '' : null,
    commandRules || null,
    '',
    `Command context: ${commandGuidance}`,
    `User request: ${userInput || 'No extra context provided.'}`
  ].filter(Boolean).join('\n');
}

module.exports = {
  buildExplainPrompt
};
